// Embeds arbitrary files (the recorded display screens) into a C++
// header/source pair.
//
// Usage: embed_files --namespace=ns --header=out.h --source=out.cc
//                    --include=pkg/out.h a.png b.png
// Generates `std::span<const EmbeddedFile> ns::Files()`, one entry per input
// in command-line order, named by the input's base name.

#include <cstdio>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

namespace {

bool StartsWith(const std::string& s, const std::string& prefix) {
  return s.compare(0, prefix.size(), prefix) == 0;
}

}  // namespace

int main(int argc, char** argv) {
  std::string ns = "embedded", header, source, include;
  std::vector<std::string> inputs;
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (StartsWith(arg, "--namespace=")) ns = arg.substr(12);
    else if (StartsWith(arg, "--header=")) header = arg.substr(9);
    else if (StartsWith(arg, "--include=")) include = arg.substr(10);
    else if (StartsWith(arg, "--source=")) source = arg.substr(9);
    else inputs.push_back(arg);
  }
  if (header.empty() || source.empty()) {
    std::fprintf(stderr, "embed_files: --header and --source are required\n");
    return 1;
  }
  if (include.empty()) include = header.substr(header.find_last_of('/') + 1);

  std::ofstream h(header), cc(source);
  h << "// Generated by embed_files. Do not edit.\n#pragma once\n\n"
    << "#include <cstddef>\n#include <span>\n\nnamespace " << ns << " {\n\n"
    << "struct EmbeddedFile {\n  const char* name;\n  const unsigned char* data;\n"
    << "  size_t size;\n};\n\nstd::span<const EmbeddedFile> Files();\n\n}  // namespace " << ns
    << "\n";
  cc << "// Generated by embed_files. Do not edit.\n#include \"" << include << "\"\n\n"
     << "namespace " << ns << " {\nnamespace {\n\n";
  for (size_t n = 0; n < inputs.size(); ++n) {
    std::ifstream f(inputs[n], std::ios::binary);
    const std::vector<char> bytes((std::istreambuf_iterator<char>(f)),
                                  std::istreambuf_iterator<char>());
    if (bytes.empty()) {
      std::fprintf(stderr, "embed_files: cannot read %s\n", inputs[n].c_str());
      return 1;
    }
    cc << "const unsigned char k" << n << "[] = {";
    for (size_t i = 0; i < bytes.size(); ++i) {
      if (i % 16 == 0) cc << "\n   ";
      char buf[8];
      std::snprintf(buf, sizeof buf, " %u,", static_cast<unsigned char>(bytes[i]));
      cc << buf;
    }
    cc << "\n};\n\n";
  }
  cc << "const EmbeddedFile kFiles[] = {\n";
  for (size_t n = 0; n < inputs.size(); ++n) {
    const std::string base = inputs[n].substr(inputs[n].find_last_of('/') + 1);
    cc << "    {\"" << base << "\", k" << n << ", sizeof k" << n << "},\n";
  }
  cc << "};\n\n}  // namespace\n\nstd::span<const EmbeddedFile> Files() { return kFiles; }\n\n"
     << "}  // namespace " << ns << "\n";
  return 0;
}
